Dev/auth
marian51/poc-playwright-typescript-gui-api pull request #11
Opened 2024-06-11 11:38 UTC by 2pavel

Added auth and a simple test using it according to:
https://playwright.dev/docs/auth

2024-06-12 11:37 UTC, marian51 requested changes
W branchu `main` pojawiło się kilka zmian po mergach tych moich pull requestów, więc można zaciągnąć te zmiany (zaktualizować branch `dev/auth` o zmiany z brancha `main`) przed mergrem tego bieżącego pull requesta 😊

2024-06-12 12:32 UTC, marian51 approved these changes

2024-06-13 08:00 UTC, shpykooh commented on page-objects/loginPage.ts
semicolons;

2024-06-13 08:03 UTC, shpykooh approved these changes
watch if prettier fixes missing semicolons.

2024-06-13 08:11 UTC, merged